GET http://localhost:3000/recipe/4 HTTP/1.1
content-type: application/json

{
    "name": "sample",
    "time": "Wed, 21 Oct 2015 18:27:50 GMT"
}


###
//TODO finish requests

POST http://localhost:3000/recipe HTTP/1.1
content-type: application/json

{
"id": 4,
  "name": "Kotlet",
  "category": [
    "Kuchnia Polska"
  ],
  "ingredients": [
    "kotlet",
    "panierka"
  ],
  "steps": [
    "Stłucz kotleta",
    "Obtocz w panierce",
    "Usmaż"
  ],
  "date": null,
  "reviews":
    {
      "user": "Allyn",
      "rating": 4,
      "likes": 420,
      "dislikes": 2,
      "content": "Najlepszy przepis na kotleta",
      "date": "2000-12-03T23:00:00.000Z"
      
    }
}