
POST  http://localhost:3000/review/627bcaf40f8f73833f89ba9e HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{
    "name":"Great recipe",
    "rating":4,
    "likes":0,
    "dislikes":0,
    "content":"Great for a family of people and friends"
    
}

###
DELETE http://localhost:3000/review/627bcaf40f8f73833f89ba9e/627bcaf40f8f73833f89baa0 HTTP/1.1
content-type: application/json
Authorization: Bearer

{

}