
GET http://localhost:3000/forum/thread/all HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{       

}


###

GET http://localhost:3000/forum/thread/62750938acebb0b5fc1ddcf0 HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{        
}

###

POST http://localhost:3000/forum/thread HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{
        "topic":"Forum rules",
        "description":"Following post contains a list of rules enforced by the administration",
        "categories":["Admin","Rules"]
}


###

PUT http://localhost:3000/forum/thread/62750a258435e24c9e540d50 HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{
    "topic":"Forum rules 2",
        "description":"Following post contains a list of rules enforced by the administration",
        "posts":[],
        "categories":["Admin","Rules"],
        "addedBy": {
            "name":"Allyn",
            "surname":"Strawpool",
            "admin":true
        },
        "post_count": 1        
}
###

PUT http://localhost:3000/forum/thread/archive/628b731cbfd7e2c0c77a4b0f HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{

}

###

DELETE http://localhost:3000/forum/thread/628b6e73a10774c7980847e8 HTTP/1.1
content-type: application/json
Authorization:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyTmFtZSI6IkFsbHluIiwibmFtZSI6IkFsYW4iLCJlbWFpbCI6IkFsbHluQGdtYWlsLmNvbSIsImFkbWluIjpmYWxzZSwic3VybmFtZSI6IlN0cmF3cG9vbCIsInBhc3N3b3JkIjoiemFxMUBXU1giLCJpYXQiOjE2NTIyNjk1NTF9.d9lPX6MZ3iuMBH4arhQkVoXO2hixlct-7jb9cGB0lm0

{            
}
